name: Sync Docs to Wiki

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/sync-docs-to-wiki.yml'

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout wiki
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki

      - name: Copy docs to wiki
        run: |
          rsync -av --delete docs/ wiki/
          cd wiki
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync docs to wiki" || echo "No changes to commit"
          git push